# coding: utf-8

"""
    bAmpli API

    Business Amplifier API  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: josemotta@bampli.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.facility_api import FacilityApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFacilityApi(unittest.TestCase):
    """FacilityApi unit test stubs"""

    def setUp(self):
        self.api = api.facility_api.FacilityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_facility(self):
        """Test case for add_facility

        Add Facility  # noqa: E501
        """
        pass

    def test_add_wip(self):
        """Test case for add_wip

        Add Wip  # noqa: E501
        """
        pass

    def test_get_facility(self):
        """Test case for get_facility

        Get Facility  # noqa: E501
        """
        pass

    def test_search_wip(self):
        """Test case for search_wip

        Get Wip  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
