# coding: utf-8

"""
    bAmpli API

    Business Amplifier API  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: josemotta@bampli.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.company_api import CompanyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCompanyApi(unittest.TestCase):
    """CompanyApi unit test stubs"""

    def setUp(self):
        self.api = api.company_api.CompanyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_company(self):
        """Test case for add_company

        Add Company  # noqa: E501
        """
        pass

    def test_add_product(self):
        """Test case for add_product

        Add Product  # noqa: E501
        """
        pass

    def test_get_company(self):
        """Test case for get_company

        Get Company  # noqa: E501
        """
        pass

    def test_get_product(self):
        """Test case for get_product

        Get Product  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
