# coding: utf-8

"""
    bAmpli API

    Business Amplifier API  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: josemotta@bampli.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.cyclo_api import CycloApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCycloApi(unittest.TestCase):
    """CycloApi unit test stubs"""

    def setUp(self):
        self.api = api.cyclo_api.CycloApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_cyclo(self):
        """Test case for add_cyclo

        Add Cyclo  # noqa: E501
        """
        pass

    def test_add_stage(self):
        """Test case for add_stage

        Add Stage  # noqa: E501
        """
        pass

    def test_add_task(self):
        """Test case for add_task

        Add Task  # noqa: E501
        """
        pass

    def test_get_cyclo(self):
        """Test case for get_cyclo

        Get Cyclo  # noqa: E501
        """
        pass

    def test_get_stage(self):
        """Test case for get_stage

        Get Stage  # noqa: E501
        """
        pass

    def test_get_task(self):
        """Test case for get_task

        Get Task  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
