# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.company_address import CompanyAddress  # noqa: F401,E501
from swagger_server import util


class Company(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, company: str=None, name: str=None, address: CompanyAddress=None):  # noqa: E501
        """Company - a model defined in Swagger

        :param company: The company of this Company.  # noqa: E501
        :type company: str
        :param name: The name of this Company.  # noqa: E501
        :type name: str
        :param address: The address of this Company.  # noqa: E501
        :type address: CompanyAddress
        """
        self.swagger_types = {
            'company': str,
            'name': str,
            'address': CompanyAddress
        }

        self.attribute_map = {
            'company': 'company',
            'name': 'name',
            'address': 'address'
        }
        self._company = company
        self._name = name
        self._address = address

    @classmethod
    def from_dict(cls, dikt) -> 'Company':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Company of this Company.  # noqa: E501
        :rtype: Company
        """
        return util.deserialize_model(dikt, cls)

    @property
    def company(self) -> str:
        """Gets the company of this Company.

        Auto-generated primary key field  # noqa: E501

        :return: The company of this Company.
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company: str):
        """Sets the company of this Company.

        Auto-generated primary key field  # noqa: E501

        :param company: The company of this Company.
        :type company: str
        """
        if company is None:
            raise ValueError("Invalid value for `company`, must not be `None`")  # noqa: E501

        self._company = company

    @property
    def name(self) -> str:
        """Gets the name of this Company.


        :return: The name of this Company.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Company.


        :param name: The name of this Company.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def address(self) -> CompanyAddress:
        """Gets the address of this Company.


        :return: The address of this Company.
        :rtype: CompanyAddress
        """
        return self._address

    @address.setter
    def address(self, address: CompanyAddress):
        """Sets the address of this Company.


        :param address: The address of this Company.
        :type address: CompanyAddress
        """
        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address
