# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Company(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, company: str=None, name: str=None, last_modified: datetime=None, home_page: str=None, phone: str=None):  # noqa: E501
        """Company - a model defined in Swagger

        :param company: The company of this Company.  # noqa: E501
        :type company: str
        :param name: The name of this Company.  # noqa: E501
        :type name: str
        :param last_modified: The last_modified of this Company.  # noqa: E501
        :type last_modified: datetime
        :param home_page: The home_page of this Company.  # noqa: E501
        :type home_page: str
        :param phone: The phone of this Company.  # noqa: E501
        :type phone: str
        """
        self.swagger_types = {
            'company': str,
            'name': str,
            'last_modified': datetime,
            'home_page': str,
            'phone': str
        }

        self.attribute_map = {
            'company': 'company',
            'name': 'name',
            'last_modified': 'lastModified',
            'home_page': 'homePage',
            'phone': 'phone'
        }
        self._company = company
        self._name = name
        self._last_modified = last_modified
        self._home_page = home_page
        self._phone = phone

    @classmethod
    def from_dict(cls, dikt) -> 'Company':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Company of this Company.  # noqa: E501
        :rtype: Company
        """
        return util.deserialize_model(dikt, cls)

    @property
    def company(self) -> str:
        """Gets the company of this Company.


        :return: The company of this Company.
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company: str):
        """Sets the company of this Company.


        :param company: The company of this Company.
        :type company: str
        """
        if company is None:
            raise ValueError("Invalid value for `company`, must not be `None`")  # noqa: E501

        self._company = company

    @property
    def name(self) -> str:
        """Gets the name of this Company.


        :return: The name of this Company.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Company.


        :param name: The name of this Company.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def last_modified(self) -> datetime:
        """Gets the last_modified of this Company.


        :return: The last_modified of this Company.
        :rtype: datetime
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified: datetime):
        """Sets the last_modified of this Company.


        :param last_modified: The last_modified of this Company.
        :type last_modified: datetime
        """
        if last_modified is None:
            raise ValueError("Invalid value for `last_modified`, must not be `None`")  # noqa: E501

        self._last_modified = last_modified

    @property
    def home_page(self) -> str:
        """Gets the home_page of this Company.


        :return: The home_page of this Company.
        :rtype: str
        """
        return self._home_page

    @home_page.setter
    def home_page(self, home_page: str):
        """Sets the home_page of this Company.


        :param home_page: The home_page of this Company.
        :type home_page: str
        """

        self._home_page = home_page

    @property
    def phone(self) -> str:
        """Gets the phone of this Company.


        :return: The phone of this Company.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this Company.


        :param phone: The phone of this Company.
        :type phone: str
        """

        self._phone = phone
