# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.company import Company  # noqa: F401,E501
from swagger_server import util


class Facility(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, facility: str=None, name: str=None, last_modified: datetime=None, company: Company=None):  # noqa: E501
        """Facility - a model defined in Swagger

        :param facility: The facility of this Facility.  # noqa: E501
        :type facility: str
        :param name: The name of this Facility.  # noqa: E501
        :type name: str
        :param last_modified: The last_modified of this Facility.  # noqa: E501
        :type last_modified: datetime
        :param company: The company of this Facility.  # noqa: E501
        :type company: Company
        """
        self.swagger_types = {
            'facility': str,
            'name': str,
            'last_modified': datetime,
            'company': Company
        }

        self.attribute_map = {
            'facility': 'facility',
            'name': 'name',
            'last_modified': 'lastModified',
            'company': 'company'
        }
        self._facility = facility
        self._name = name
        self._last_modified = last_modified
        self._company = company

    @classmethod
    def from_dict(cls, dikt) -> 'Facility':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Facility of this Facility.  # noqa: E501
        :rtype: Facility
        """
        return util.deserialize_model(dikt, cls)

    @property
    def facility(self) -> str:
        """Gets the facility of this Facility.


        :return: The facility of this Facility.
        :rtype: str
        """
        return self._facility

    @facility.setter
    def facility(self, facility: str):
        """Sets the facility of this Facility.


        :param facility: The facility of this Facility.
        :type facility: str
        """
        if facility is None:
            raise ValueError("Invalid value for `facility`, must not be `None`")  # noqa: E501

        self._facility = facility

    @property
    def name(self) -> str:
        """Gets the name of this Facility.


        :return: The name of this Facility.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Facility.


        :param name: The name of this Facility.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def last_modified(self) -> datetime:
        """Gets the last_modified of this Facility.


        :return: The last_modified of this Facility.
        :rtype: datetime
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified: datetime):
        """Sets the last_modified of this Facility.


        :param last_modified: The last_modified of this Facility.
        :type last_modified: datetime
        """
        if last_modified is None:
            raise ValueError("Invalid value for `last_modified`, must not be `None`")  # noqa: E501

        self._last_modified = last_modified

    @property
    def company(self) -> Company:
        """Gets the company of this Facility.


        :return: The company of this Facility.
        :rtype: Company
        """
        return self._company

    @company.setter
    def company(self, company: Company):
        """Sets the company of this Facility.


        :param company: The company of this Facility.
        :type company: Company
        """
        if company is None:
            raise ValueError("Invalid value for `company`, must not be `None`")  # noqa: E501

        self._company = company
