# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.company import Company  # noqa: F401,E501
from swagger_server import util


class Product(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, product: str=None, name: str=None, last_modified: datetime=None, company: Company=None):  # noqa: E501
        """Product - a model defined in Swagger

        :param product: The product of this Product.  # noqa: E501
        :type product: str
        :param name: The name of this Product.  # noqa: E501
        :type name: str
        :param last_modified: The last_modified of this Product.  # noqa: E501
        :type last_modified: datetime
        :param company: The company of this Product.  # noqa: E501
        :type company: Company
        """
        self.swagger_types = {
            'product': str,
            'name': str,
            'last_modified': datetime,
            'company': Company
        }

        self.attribute_map = {
            'product': 'product',
            'name': 'name',
            'last_modified': 'lastModified',
            'company': 'company'
        }
        self._product = product
        self._name = name
        self._last_modified = last_modified
        self._company = company

    @classmethod
    def from_dict(cls, dikt) -> 'Product':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Product of this Product.  # noqa: E501
        :rtype: Product
        """
        return util.deserialize_model(dikt, cls)

    @property
    def product(self) -> str:
        """Gets the product of this Product.


        :return: The product of this Product.
        :rtype: str
        """
        return self._product

    @product.setter
    def product(self, product: str):
        """Sets the product of this Product.


        :param product: The product of this Product.
        :type product: str
        """
        if product is None:
            raise ValueError("Invalid value for `product`, must not be `None`")  # noqa: E501

        self._product = product

    @property
    def name(self) -> str:
        """Gets the name of this Product.


        :return: The name of this Product.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Product.


        :param name: The name of this Product.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def last_modified(self) -> datetime:
        """Gets the last_modified of this Product.


        :return: The last_modified of this Product.
        :rtype: datetime
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified: datetime):
        """Sets the last_modified of this Product.


        :param last_modified: The last_modified of this Product.
        :type last_modified: datetime
        """
        if last_modified is None:
            raise ValueError("Invalid value for `last_modified`, must not be `None`")  # noqa: E501

        self._last_modified = last_modified

    @property
    def company(self) -> Company:
        """Gets the company of this Product.


        :return: The company of this Product.
        :rtype: Company
        """
        return self._company

    @company.setter
    def company(self, company: Company):
        """Sets the company of this Product.


        :param company: The company of this Product.
        :type company: Company
        """
        if company is None:
            raise ValueError("Invalid value for `company`, must not be `None`")  # noqa: E501

        self._company = company
