# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Stage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, stage: str=None, name: str=None, active: bool=True, cyclo: str=None):  # noqa: E501
        """Stage - a model defined in Swagger

        :param stage: The stage of this Stage.  # noqa: E501
        :type stage: str
        :param name: The name of this Stage.  # noqa: E501
        :type name: str
        :param active: The active of this Stage.  # noqa: E501
        :type active: bool
        :param cyclo: The cyclo of this Stage.  # noqa: E501
        :type cyclo: str
        """
        self.swagger_types = {
            'stage': str,
            'name': str,
            'active': bool,
            'cyclo': str
        }

        self.attribute_map = {
            'stage': 'stage',
            'name': 'name',
            'active': 'active',
            'cyclo': 'cyclo'
        }
        self._stage = stage
        self._name = name
        self._active = active
        self._cyclo = cyclo

    @classmethod
    def from_dict(cls, dikt) -> 'Stage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Stage of this Stage.  # noqa: E501
        :rtype: Stage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def stage(self) -> str:
        """Gets the stage of this Stage.

        Auto-generated primary key field  # noqa: E501

        :return: The stage of this Stage.
        :rtype: str
        """
        return self._stage

    @stage.setter
    def stage(self, stage: str):
        """Sets the stage of this Stage.

        Auto-generated primary key field  # noqa: E501

        :param stage: The stage of this Stage.
        :type stage: str
        """
        if stage is None:
            raise ValueError("Invalid value for `stage`, must not be `None`")  # noqa: E501

        self._stage = stage

    @property
    def name(self) -> str:
        """Gets the name of this Stage.


        :return: The name of this Stage.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Stage.


        :param name: The name of this Stage.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def active(self) -> bool:
        """Gets the active of this Stage.


        :return: The active of this Stage.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active: bool):
        """Sets the active of this Stage.


        :param active: The active of this Stage.
        :type active: bool
        """

        self._active = active

    @property
    def cyclo(self) -> str:
        """Gets the cyclo of this Stage.

        This property is a reference to a Cyclo  # noqa: E501

        :return: The cyclo of this Stage.
        :rtype: str
        """
        return self._cyclo

    @cyclo.setter
    def cyclo(self, cyclo: str):
        """Sets the cyclo of this Stage.

        This property is a reference to a Cyclo  # noqa: E501

        :param cyclo: The cyclo of this Stage.
        :type cyclo: str
        """
        if cyclo is None:
            raise ValueError("Invalid value for `cyclo`, must not be `None`")  # noqa: E501

        self._cyclo = cyclo
