# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.cyclo import Cyclo  # noqa: F401,E501
from swagger_server import util


class Stage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, stage: str=None, name: str=None, last_modified: datetime=None, cyclo: Cyclo=None):  # noqa: E501
        """Stage - a model defined in Swagger

        :param stage: The stage of this Stage.  # noqa: E501
        :type stage: str
        :param name: The name of this Stage.  # noqa: E501
        :type name: str
        :param last_modified: The last_modified of this Stage.  # noqa: E501
        :type last_modified: datetime
        :param cyclo: The cyclo of this Stage.  # noqa: E501
        :type cyclo: Cyclo
        """
        self.swagger_types = {
            'stage': str,
            'name': str,
            'last_modified': datetime,
            'cyclo': Cyclo
        }

        self.attribute_map = {
            'stage': 'stage',
            'name': 'name',
            'last_modified': 'lastModified',
            'cyclo': 'cyclo'
        }
        self._stage = stage
        self._name = name
        self._last_modified = last_modified
        self._cyclo = cyclo

    @classmethod
    def from_dict(cls, dikt) -> 'Stage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Stage of this Stage.  # noqa: E501
        :rtype: Stage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def stage(self) -> str:
        """Gets the stage of this Stage.


        :return: The stage of this Stage.
        :rtype: str
        """
        return self._stage

    @stage.setter
    def stage(self, stage: str):
        """Sets the stage of this Stage.


        :param stage: The stage of this Stage.
        :type stage: str
        """
        if stage is None:
            raise ValueError("Invalid value for `stage`, must not be `None`")  # noqa: E501

        self._stage = stage

    @property
    def name(self) -> str:
        """Gets the name of this Stage.


        :return: The name of this Stage.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Stage.


        :param name: The name of this Stage.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def last_modified(self) -> datetime:
        """Gets the last_modified of this Stage.


        :return: The last_modified of this Stage.
        :rtype: datetime
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified: datetime):
        """Sets the last_modified of this Stage.


        :param last_modified: The last_modified of this Stage.
        :type last_modified: datetime
        """
        if last_modified is None:
            raise ValueError("Invalid value for `last_modified`, must not be `None`")  # noqa: E501

        self._last_modified = last_modified

    @property
    def cyclo(self) -> Cyclo:
        """Gets the cyclo of this Stage.


        :return: The cyclo of this Stage.
        :rtype: Cyclo
        """
        return self._cyclo

    @cyclo.setter
    def cyclo(self, cyclo: Cyclo):
        """Sets the cyclo of this Stage.


        :param cyclo: The cyclo of this Stage.
        :type cyclo: Cyclo
        """
        if cyclo is None:
            raise ValueError("Invalid value for `cyclo`, must not be `None`")  # noqa: E501

        self._cyclo = cyclo
