# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.stage import Stage  # noqa: F401,E501
from swagger_server import util


class Task(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, task: str=None, name: str=None, last_modified: datetime=None, stage: Stage=None):  # noqa: E501
        """Task - a model defined in Swagger

        :param task: The task of this Task.  # noqa: E501
        :type task: str
        :param name: The name of this Task.  # noqa: E501
        :type name: str
        :param last_modified: The last_modified of this Task.  # noqa: E501
        :type last_modified: datetime
        :param stage: The stage of this Task.  # noqa: E501
        :type stage: Stage
        """
        self.swagger_types = {
            'task': str,
            'name': str,
            'last_modified': datetime,
            'stage': Stage
        }

        self.attribute_map = {
            'task': 'task',
            'name': 'name',
            'last_modified': 'lastModified',
            'stage': 'stage'
        }
        self._task = task
        self._name = name
        self._last_modified = last_modified
        self._stage = stage

    @classmethod
    def from_dict(cls, dikt) -> 'Task':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Task of this Task.  # noqa: E501
        :rtype: Task
        """
        return util.deserialize_model(dikt, cls)

    @property
    def task(self) -> str:
        """Gets the task of this Task.


        :return: The task of this Task.
        :rtype: str
        """
        return self._task

    @task.setter
    def task(self, task: str):
        """Sets the task of this Task.


        :param task: The task of this Task.
        :type task: str
        """
        if task is None:
            raise ValueError("Invalid value for `task`, must not be `None`")  # noqa: E501

        self._task = task

    @property
    def name(self) -> str:
        """Gets the name of this Task.


        :return: The name of this Task.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Task.


        :param name: The name of this Task.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def last_modified(self) -> datetime:
        """Gets the last_modified of this Task.


        :return: The last_modified of this Task.
        :rtype: datetime
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified: datetime):
        """Sets the last_modified of this Task.


        :param last_modified: The last_modified of this Task.
        :type last_modified: datetime
        """
        if last_modified is None:
            raise ValueError("Invalid value for `last_modified`, must not be `None`")  # noqa: E501

        self._last_modified = last_modified

    @property
    def stage(self) -> Stage:
        """Gets the stage of this Task.


        :return: The stage of this Task.
        :rtype: Stage
        """
        return self._stage

    @stage.setter
    def stage(self, stage: Stage):
        """Sets the stage of this Task.


        :param stage: The stage of this Task.
        :type stage: Stage
        """
        if stage is None:
            raise ValueError("Invalid value for `stage`, must not be `None`")  # noqa: E501

        self._stage = stage
