# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Task(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, task: str=None, name: str=None, active: bool=True, stage: str=None):  # noqa: E501
        """Task - a model defined in Swagger

        :param task: The task of this Task.  # noqa: E501
        :type task: str
        :param name: The name of this Task.  # noqa: E501
        :type name: str
        :param active: The active of this Task.  # noqa: E501
        :type active: bool
        :param stage: The stage of this Task.  # noqa: E501
        :type stage: str
        """
        self.swagger_types = {
            'task': str,
            'name': str,
            'active': bool,
            'stage': str
        }

        self.attribute_map = {
            'task': 'task',
            'name': 'name',
            'active': 'active',
            'stage': 'stage'
        }
        self._task = task
        self._name = name
        self._active = active
        self._stage = stage

    @classmethod
    def from_dict(cls, dikt) -> 'Task':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Task of this Task.  # noqa: E501
        :rtype: Task
        """
        return util.deserialize_model(dikt, cls)

    @property
    def task(self) -> str:
        """Gets the task of this Task.

        Auto-generated primary key field  # noqa: E501

        :return: The task of this Task.
        :rtype: str
        """
        return self._task

    @task.setter
    def task(self, task: str):
        """Sets the task of this Task.

        Auto-generated primary key field  # noqa: E501

        :param task: The task of this Task.
        :type task: str
        """
        if task is None:
            raise ValueError("Invalid value for `task`, must not be `None`")  # noqa: E501

        self._task = task

    @property
    def name(self) -> str:
        """Gets the name of this Task.


        :return: The name of this Task.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Task.


        :param name: The name of this Task.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def active(self) -> bool:
        """Gets the active of this Task.


        :return: The active of this Task.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active: bool):
        """Sets the active of this Task.


        :param active: The active of this Task.
        :type active: bool
        """

        self._active = active

    @property
    def stage(self) -> str:
        """Gets the stage of this Task.

        This property is a reference to a Stage  # noqa: E501

        :return: The stage of this Task.
        :rtype: str
        """
        return self._stage

    @stage.setter
    def stage(self, stage: str):
        """Sets the stage of this Task.

        This property is a reference to a Stage  # noqa: E501

        :param stage: The stage of this Task.
        :type stage: str
        """
        if stage is None:
            raise ValueError("Invalid value for `stage`, must not be `None`")  # noqa: E501

        self._stage = stage
