# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Wip(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, wip: str=None, name: str=None, active: bool=True, facility: str=None):  # noqa: E501
        """Wip - a model defined in Swagger

        :param wip: The wip of this Wip.  # noqa: E501
        :type wip: str
        :param name: The name of this Wip.  # noqa: E501
        :type name: str
        :param active: The active of this Wip.  # noqa: E501
        :type active: bool
        :param facility: The facility of this Wip.  # noqa: E501
        :type facility: str
        """
        self.swagger_types = {
            'wip': str,
            'name': str,
            'active': bool,
            'facility': str
        }

        self.attribute_map = {
            'wip': 'wip',
            'name': 'name',
            'active': 'active',
            'facility': 'facility'
        }
        self._wip = wip
        self._name = name
        self._active = active
        self._facility = facility

    @classmethod
    def from_dict(cls, dikt) -> 'Wip':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Wip of this Wip.  # noqa: E501
        :rtype: Wip
        """
        return util.deserialize_model(dikt, cls)

    @property
    def wip(self) -> str:
        """Gets the wip of this Wip.

        Auto-generated primary key field  # noqa: E501

        :return: The wip of this Wip.
        :rtype: str
        """
        return self._wip

    @wip.setter
    def wip(self, wip: str):
        """Sets the wip of this Wip.

        Auto-generated primary key field  # noqa: E501

        :param wip: The wip of this Wip.
        :type wip: str
        """
        if wip is None:
            raise ValueError("Invalid value for `wip`, must not be `None`")  # noqa: E501

        self._wip = wip

    @property
    def name(self) -> str:
        """Gets the name of this Wip.


        :return: The name of this Wip.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Wip.


        :param name: The name of this Wip.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def active(self) -> bool:
        """Gets the active of this Wip.


        :return: The active of this Wip.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active: bool):
        """Sets the active of this Wip.


        :param active: The active of this Wip.
        :type active: bool
        """

        self._active = active

    @property
    def facility(self) -> str:
        """Gets the facility of this Wip.

        This property is a reference to a Facility  # noqa: E501

        :return: The facility of this Wip.
        :rtype: str
        """
        return self._facility

    @facility.setter
    def facility(self, facility: str):
        """Sets the facility of this Wip.

        This property is a reference to a Facility  # noqa: E501

        :param facility: The facility of this Wip.
        :type facility: str
        """
        if facility is None:
            raise ValueError("Invalid value for `facility`, must not be `None`")  # noqa: E501

        self._facility = facility
