/**
 * bampli-api
 * The API for the Business Amplifier project.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: josemotta@bampli.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CompanyAddress } from './companyAddress';

/**
 * A representation of a Company.
 */
export interface Company { 
    /**
     * Auto-generated primary key field
     */
    companyId: string;
    name: string;
    address: CompanyAddress;
}