# coding: utf-8

"""
    bampli-api

    The API for the Business Amplifier project  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: josemotta@bampli.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Contact(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'contact': 'str',
        'first_name': 'str',
        'last_name': 'str',
        'tax_id': 'str',
        'birthday': 'int',
        'active': 'bool',
        'company': 'str'
    }

    attribute_map = {
        'contact': 'contact',
        'first_name': 'firstName',
        'last_name': 'lastName',
        'tax_id': 'taxId',
        'birthday': 'birthday',
        'active': 'active',
        'company': 'company'
    }

    def __init__(self, contact=None, first_name=None, last_name=None, tax_id=None, birthday=None, active=True, company=None):  # noqa: E501
        """Contact - a model defined in Swagger"""  # noqa: E501
        self._contact = None
        self._first_name = None
        self._last_name = None
        self._tax_id = None
        self._birthday = None
        self._active = None
        self._company = None
        self.discriminator = None
        self.contact = contact
        self.first_name = first_name
        self.last_name = last_name
        if tax_id is not None:
            self.tax_id = tax_id
        if birthday is not None:
            self.birthday = birthday
        if active is not None:
            self.active = active
        self.company = company

    @property
    def contact(self):
        """Gets the contact of this Contact.  # noqa: E501

        Auto-generated primary key field  # noqa: E501

        :return: The contact of this Contact.  # noqa: E501
        :rtype: str
        """
        return self._contact

    @contact.setter
    def contact(self, contact):
        """Sets the contact of this Contact.

        Auto-generated primary key field  # noqa: E501

        :param contact: The contact of this Contact.  # noqa: E501
        :type: str
        """
        if contact is None:
            raise ValueError("Invalid value for `contact`, must not be `None`")  # noqa: E501

        self._contact = contact

    @property
    def first_name(self):
        """Gets the first_name of this Contact.  # noqa: E501


        :return: The first_name of this Contact.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this Contact.


        :param first_name: The first_name of this Contact.  # noqa: E501
        :type: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this Contact.  # noqa: E501


        :return: The last_name of this Contact.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this Contact.


        :param last_name: The last_name of this Contact.  # noqa: E501
        :type: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501

        self._last_name = last_name

    @property
    def tax_id(self):
        """Gets the tax_id of this Contact.  # noqa: E501


        :return: The tax_id of this Contact.  # noqa: E501
        :rtype: str
        """
        return self._tax_id

    @tax_id.setter
    def tax_id(self, tax_id):
        """Sets the tax_id of this Contact.


        :param tax_id: The tax_id of this Contact.  # noqa: E501
        :type: str
        """

        self._tax_id = tax_id

    @property
    def birthday(self):
        """Gets the birthday of this Contact.  # noqa: E501

        Birthday as unix timestamp (in ms)  # noqa: E501

        :return: The birthday of this Contact.  # noqa: E501
        :rtype: int
        """
        return self._birthday

    @birthday.setter
    def birthday(self, birthday):
        """Sets the birthday of this Contact.

        Birthday as unix timestamp (in ms)  # noqa: E501

        :param birthday: The birthday of this Contact.  # noqa: E501
        :type: int
        """

        self._birthday = birthday

    @property
    def active(self):
        """Gets the active of this Contact.  # noqa: E501


        :return: The active of this Contact.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this Contact.


        :param active: The active of this Contact.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def company(self):
        """Gets the company of this Contact.  # noqa: E501

        This property is a reference to a Company  # noqa: E501

        :return: The company of this Contact.  # noqa: E501
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company):
        """Sets the company of this Contact.

        This property is a reference to a Company  # noqa: E501

        :param company: The company of this Contact.  # noqa: E501
        :type: str
        """
        if company is None:
            raise ValueError("Invalid value for `company`, must not be `None`")  # noqa: E501

        self._company = company

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Contact, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Contact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
