# coding: utf-8

"""
    bAmpli API

    Business Amplifier API  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: josemotta@bampli.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Wip(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'wip': 'str',
        'name': 'str',
        'last_modified': 'datetime',
        'facility': 'Facility'
    }

    attribute_map = {
        'wip': 'wip',
        'name': 'name',
        'last_modified': 'lastModified',
        'facility': 'facility'
    }

    def __init__(self, wip=None, name=None, last_modified=None, facility=None):  # noqa: E501
        """Wip - a model defined in Swagger"""  # noqa: E501
        self._wip = None
        self._name = None
        self._last_modified = None
        self._facility = None
        self.discriminator = None
        self.wip = wip
        self.name = name
        self.last_modified = last_modified
        self.facility = facility

    @property
    def wip(self):
        """Gets the wip of this Wip.  # noqa: E501


        :return: The wip of this Wip.  # noqa: E501
        :rtype: str
        """
        return self._wip

    @wip.setter
    def wip(self, wip):
        """Sets the wip of this Wip.


        :param wip: The wip of this Wip.  # noqa: E501
        :type: str
        """
        if wip is None:
            raise ValueError("Invalid value for `wip`, must not be `None`")  # noqa: E501

        self._wip = wip

    @property
    def name(self):
        """Gets the name of this Wip.  # noqa: E501


        :return: The name of this Wip.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Wip.


        :param name: The name of this Wip.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def last_modified(self):
        """Gets the last_modified of this Wip.  # noqa: E501


        :return: The last_modified of this Wip.  # noqa: E501
        :rtype: datetime
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified):
        """Sets the last_modified of this Wip.


        :param last_modified: The last_modified of this Wip.  # noqa: E501
        :type: datetime
        """
        if last_modified is None:
            raise ValueError("Invalid value for `last_modified`, must not be `None`")  # noqa: E501

        self._last_modified = last_modified

    @property
    def facility(self):
        """Gets the facility of this Wip.  # noqa: E501


        :return: The facility of this Wip.  # noqa: E501
        :rtype: Facility
        """
        return self._facility

    @facility.setter
    def facility(self, facility):
        """Sets the facility of this Wip.


        :param facility: The facility of this Wip.  # noqa: E501
        :type: Facility
        """
        if facility is None:
            raise ValueError("Invalid value for `facility`, must not be `None`")  # noqa: E501

        self._facility = facility

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Wip, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Wip):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
